import streamlit as st
from frontend.components.style import load_css

st.set_page_config(
    page_title="Y2H-AI Molecular Observatory",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Apply custom premium CSS
load_css()

st.title("🧬 Y2H-AI Molecular Observatory")
st.markdown("### AI-driven computational platform for exploring yeast protein–protein interaction hypotheses.")

st.markdown("---")

st.markdown("""
Welcome to the V3 visualization upgrade of the Y2H-AI platform. 

This environment is designed as a **computational biology instrument** for hypothesis generation and structural visualization, powered by the underlying robust, validated pipeline:

- **Real BioGRID Y2H data**
- **Strict Protein-disjoint (C1/C2/C3) evaluation**
- **Calibrated Random Forest predictions**
- **Reproducible data provenance**

### 🧭 Navigation
Please use the sidebar to navigate the observatory:

1. **🔬 Interaction Laboratory**: The flagship tool to input protein pairs, predict interactions, and view conceptual 3D models.
2. **🧬 Protein Observatory**: Inspect individual protein sequences and topological characteristics.
3. **🌐 3D Network Explorer**: View the 3D neighborhood of known proteins and computationally expand missing interactions.
4. **📊 Model Reliability**: Scrutinize the C1/C2/C3 generalization gap and feature ablation studies.
5. **📚 Methods & Provenance**: Audit the raw pipeline manifests and limitations.

---
### Enter the Observatory

<div style="margin-bottom: 20px;"></div>
""", unsafe_allow_html=True)
col_nav1, col_nav2, col_nav3 = st.columns(3)

with col_nav1:
    st.page_link("frontend/pages/01_Interaction_Laboratory.py", label="**Analyze Interaction**", icon="🔬")
    st.caption("Explore two proteins and generate interactive 3D visualizations.")

with col_nav2:
    st.page_link("frontend/pages/03_3D_Network_Explorer.py", label="**Explore Interaction Network**", icon="🌐")
    st.caption("Navigate protein neighborhoods and expand candidates.")
    
with col_nav3:
    st.page_link("frontend/pages/04_Model_Observatory.py", label="**Examine Model Reliability**", icon="📊")
    st.caption("Inspect C1/C2/C3 generalization and feature ablation results.")

st.markdown("<br><br>### Scientific Status", unsafe_allow_html=True)

st.markdown("""
<div style='display: flex; gap: 20px; flex-wrap: wrap;'>
    <div class='premium-card' style='flex: 1; min-width: 300px;'>
        <h4><span style='color: #38BDF8;'>01</span> Scientific Honesty First</h4>
        <p>No predicted edge is rendered as a documented physical bond. Absence of a structural interface does not mean no interaction.</p>
    </div>
    <div class='premium-card' style='flex: 1; min-width: 300px;'>
        <h4><span style='color: #10B981;'>02</span> Data Provenance</h4>
        <p>Every probability readout traces back to canonical, reproducible JSON artifacts generated by the batch pipeline.</p>
    </div>
    <div class='premium-card' style='flex: 1; min-width: 300px;'>
        <h4><span style='color: #F59E0B;'>03</span> Hypothesis Only</h4>
        <p>Predictions are strictly computational prioritizations intended for wet-lab follow up, not confirmed biology.</p>
    </div>
</div>
""", unsafe_allow_html=True)
